### ISSUE TITLE
Container exception if SwiftMailerBundle is installed but not loaded

### ISSUE THREAD

**Issue by xelaris** [Sylius/SyliusMailerBundle#167]
**SyliusMailerBundle version affected**: 1.8.0

**Description**  
Upgrading from 1.7.0. to 1.8.0 causes the following error:

> In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86: The service "sylius.email_sender.adapter.swiftmailer" has a dependency on a non-existent service "swiftmailer.mailer.default".

Version 1.8.0 decides, wether to remove or not remove the `sylius.email_sender.adapter.swiftmailer` service, by leveraging `ContainerBuilder::willBeAvailable`, which checks for the package to be installed, but not if the bundle is actually loaded.

We are using a custom sender adapter, which doesn't rely on SwiftMailer, thus the SwiftMailerBundle isn't loaded in the application. Although swiftmailer/swiftmailer and symfony/swiftmailer-bundle are installed as a transitive dependency of Sylius (1.11.7).

Hence `sylius.email_sender.adapter.swiftmailer` ends up in the container, while the dependency `swiftmailer.mailer.default` doesn't.

**Steps to reproduce**  
Upgrade to sylius/mailer-bundle 1.8.0 in a Sylius 1.11.7 application, without having the SwiftMailerBundle loaded (no entry in bundles.php).

**Possible Solution**  
Checking if the SwiftmailerBundle is actually loaded, would do the trick, although I'm not sure if it's possible at that point within the `SyliusMailerExtension` (maybe at least the order within bundles.php would matter?).

As a workaround we are adding `"conflict": { "sylius/mailer-bundle": "^1.8.0" }` to composer.json.

**Comment by mbabker** [comment]
The `kernel.bundles` container parameter is always able to check whether a bundle is enabled when the container is compiled (the kernel sets that and a few other parameters before anything else starts processing); checking if a service exists though is only fairly reliable in compiler passes as that can be easily influenced by the order in which bundles are loaded and logic in the container extension classes.  But, I'd personally argue that if you have to check the list of enabled bundles AND the `ContainerBuilder::willBeAvailable()` result, there is a deeper issue that needs to be addressed.

In your case, since you're not even loading `SwiftmailerBundle` in your application, I'd say a combination of explicitly configuring the sender adapter (which it sounds like is already happening) plus a compiler pass removing the Swift Mailer adapter from your app's container would work.  It's ugly, but I think that runs into a bit of an edge case with `ContainerBuilder::willBeAvailable()` and dealing with that is better suited for the Symfony repo than trying to hack around it in downstream repos.
