### ISSUE TITLE
Support for newest Symfony mailer

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/SyliusMailerBundle#5]
According to this comment: https://symfony.com/blog/new-in-symfony-4-3-mailer-component#comment-23375 we should prepare for November, when swift mailer may be replaced by Symfony/Mailer

**Comment by pamil** [comment]
Symfony's Mailer seems to do almost all the things that Sylius' Mailer does, so I think it'll effectively replace our bundle and component as well.

From my point of view, we should do the following things in the next minor release:
 - add an adapter for Symfony Mailer
 - deprecate our bundle and component

**Comment by lchrusciel** [comment]
Seems perfect to me 👍

**Comment by Roshyo** [comment]
Where are we on this one ?
I would just have a question, would the devs/plugin made using this have to be rewritten ?

**Comment by lchrusciel** [comment]
As we want to keep as close as possible to Symfony stack, once there is a better, official implementation of the package we want to move. 

However, due to our bc-policy, we would like to provide a seamless upgrade path, so they would rather be adjusted, or nothing will be required. Nevertheless, this bundle will probably be deprecated and not extended anymore.

**Comment by arjanfrans** [comment]
I just implemented a Symfony Messenger Mailer adapter. However, I had a problem when running my consumer async (but I guess the same problem occurs with Swiftmailer running with a file spool? I haven't tried that).

I am using the Sylius Invoice Bundle which adds PDF attachments to the e-mails. These attachments get deleted right away and therfore my consumer can not send the e-mails because the files are gone. 

To solve this I created a system that adds a unique id to e-mails, stores the files and after handling the SendEmailMessage from Symfony I delete the files again using an eventlistener on WorkerMessageHandledEvent.

In my opinion Sylius should support this out-of-the-box. Right now it doesn't seem to be possible to send e-mails with attachment asynchronously. Please correct me if I am wrong.

**Comment by rimas-kudelis** [comment]
I have a working implementation of async and attachments. @arjanfrans you just have to use `$email->attach()` instead of `$email->attachFromPath()`. There used to be a problem with using Doctrine for storing queued messages (symfony/symfony#33913), but it's been fixed in January, so it shouldn't cause issues anymore.

**Comment by arjanfrans** [comment]
Yes, of course that would work. The thing is that I'd like to avoid storing binary files in the message queue.

**Comment by rimas-kudelis** [comment]
Oh.

**Comment by mbabker** [comment]
Based on https://symfony.com/blog/the-end-of-swiftmailer it's probably a good idea to come up with a game plan to move forward on this.

**Comment by mbabker** [comment]
I'm kind of mixed on what to do with this package as I've been doing a heavy mail-based project this week (adding mail features to the non-shop part of a Sylius build).  On one hand, I do think Mailer is well enough integrated with Symfony that an abstraction layer (especially one that makes using some of the mailer component's features a complete pain) isn't necessary.  On the other hand, I do think there are some minor convenience features here that make managing emails a bit better overall.  No matter what though, #102 does need to ship to unblock Symfony 6 support and help with a future deprecation of this package since users would have the replacement installed and be able to work on the migration in small bits.

Pros:
- It has a centralized configuration for a known list of emails with high-level settings on those emails (template paths, subject lines, sender addresses)
- Abstraction layer that keeps things from being 100% hard coupled to Twig and SwiftMailer or Symfony's Mailer component (which, could be a pro or con; the Symfony ecosystem is pretty much hard coupled to Twig and Mailer so it could be a needless abstraction)

Cons:
- Email rendering paths are different (this package requires rendered bodies, using Twig Bridge + Mailer you can provide template paths that are rendered later on)
- Twig rendering logic is different (Twig Bridge + Mailer renders templates in full, this package has separate top-level blocks for the subject and body, which makes the templates require a migration to switch to Mailer)
- There is no way to provide a plain-text email body without overloading the rendering adapter, sending adapter, and `RenderedEmail` DTO at a minimum (see my code snippet below for the hacky way I'm pulling this off in my custom Twig adapter)
- Message subject handling (the subject configuration was deprecated IIRC to allow localized subjects, which use Twig blocks to accomplish; you'd have to move the handling for that to the email manager PHP classes, assuming those don't go away)

```php
private function provideEmailWithTemplate(EmailInterface $email, array $data): SyliusRenderedEmail
{
    $data = $this->twig->mergeGlobals($data);

    $template = $this->twig->loadTemplate((string) $email->getTemplate());

    $subject = $template->renderBlock('subject', $data);
    $body = $template->renderBlock('body', $data);

    /*
     * START PLAIN-TEXT HACK
     */
    $plainBody = null;

    $plainTemplateName = str_replace('html.twig', 'txt.twig', (string) $email->getTemplate());

    if ($this->twig->getLoader()->exists($plainTemplateName)) {
        $plainTemplate = $this->twig->loadTemplate($plainTemplateName);

        $plainBody = $plainTemplate->renderBlock('body', $data);
    }

    return new RenderedEmail($subject, $body, $plainBody);
}
```

**Comment by rimas-kudelis** [comment]
I have an interesting use-case as well, which, even if not very useful, may at least be interesting, so let me share it with you.

I'm currently working on a project which wants to send ALL emails via a third-party service called [Omnisend](https://www.omnisend.com/), but here's the thing: Omnisend composes emails itself! What you do is trigger a custom event via its API with a bunch of field values (event name, recipient, and any custom values you want), and Omnisend places those values in the template that you prepare in advance in its admin panel. So, I don't think that this whole notion of "Email Renderer" and "Rendered Email Sender Adapter" as two separate services called by Sylius Mailer would work with Omnisend. 

My current line of thought is to replace `Sylius\Component\Mailer\Sender\Sender` with a custom service implementing the same interface, but deferring to Omnisend instead. The I of course will have to override the `sylius.email_sender` service to point to mine. I wonder if I would have to do something similar with Symfony Mailer, or if it could be used as an adapter instead (probably not?). Or if switching to Symfony Mailer would complicate things even further for a case like this.

BTW, there's [Omnisend plugin for Sylius](https://github.com/nfq-technologies/sylius-omnisend-plugin), but it doesn't seem to replace mailer at the moment, instead focusing on sync/export of catalog and customers.

**Comment by rimas-kudelis** [comment]
Anyways, back to your reply, the list of cons of retaining this bundle is tree times as bit as a list or pros. Furthermore, considering that Symfony Mailer is an abstraction itself, I whileheartedly agree that an abstraction-over-abstraction, which Sylius Mailer in this case is, is absolutely unnecessary and is just a needless complication of things.

**Comment by vasilvestre** [comment]
Swiftmailer isn't maintained anymore, it seems worth to support the new mailer now

**Comment by Zales0123** [comment]
I believe it can be closed now 🖖
